4.1 Exercise on Functions:
Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def convert_length (value, unit) :
  """
  Converts length between meters and feet.
  param value: the numeric value to convert
  param unit: unit of given value ('m' for meters, 'ft for feet')
  return : Converted value
  """
  if unit == 'm':
    return value * 3.28084 #meters to feet
  elif unit == 'ft':
    return value / 3.28084 #feet to meters
  else:
    raise ValueError("Unsupported length unit")
def convert_weight (value, unit):
  """
  Converts weight between kilograms and pounds.
  param value: the numeric value to convert
  param unit: unit of given value ('kg' for kilograms, 'lb' for pounds)
  return : Converted value
  """
  if unit == 'kg':
    return value * 2.20462 #kilograms to pound
  elif unit == 'lb':
    return value / 2.20462 #pounds to kilogram
  else :
    raise ValueError("Unsupported weight unit");

def convert_volume (value, unit):
  """
  converts volume between liters and gallons.
  param value: the numeric value to convert
  param unit: unit of given value ('l' for liters, 'gal' for gallons).
  """
  if unit == 'l' :
    return value * 0.264172 #liters to gallons
  elif unit == 'gal' :
    return value / 0.264172 #gallons to liters
  else :
    raise ValueError("Unsupported volume unit")
def main() :
  print("Choose conversion type : \n 1. Length (m-ft) \n 2. Weight (lg-lbs) \n 3. Volume (L-gal) \n")
  try : 
    choice = int(input("Enter your choice (1/2/3) : "))
    if choice not in [1, 2, 3] :
      print("Invalid choice. Please enter 1/2/3")
      return
    value = int(input("Enter value to convert: "))
    if choice == 1 :
      unit = input("Enter unit (m/ft) : ")
      print(f"Converted value : {convert_length(value, unit)}")
    elif choice == 2 :
      unit = input("Enter unit (kg/lb) : ")
      print(f"Converted value : {convert_weight(value, unit)}")
    elif choice == 3 :
      unit = input("Enter unit (l/gal) : ")
      print(f"Converted value : {convert_volume(value, unit)}")
  except ValueError as e :
      print(f"Error: {e}. Please enter a valid numeric value and unit")
  except Exception as e :
      print(f"An unexpected error occurred: {e}")
if __name__ == "__main__":
  main()





Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

6CS012 Worksheet - 0 Siman Giri

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def calculate_sum(numbers):
  """
  Calculcates the sum of a list of numbers.
  param numbers: list of numbers
  return : sum of numbers
  """
  return sum(numbers)

def calculates_average(numbers):
  """
  Calculcates the average of a list of numbers.
  param numbers: list of numbers
  return : average of numbers
  """
  return sum(numbers) / len(numbers) if numbers else 0

def find_max(numbers):
  """
  Finds the maximum value in a list of numbers.
  param numbers: list of numbers
  return : maximum value in the list
  """
  return max(numbers) if numbers else None

def find_min(numbers):
  """
  Finds the minimum value in a list of numbers.
  param numbers: list of numbers
  return : minimum value in the list
  """
  return min(numbers) if numbers else None 
def main():
  print("Choose an operation")
  print("1. Calculate Sum")
  print("2. Calculate Average")
  print("3. Find Maximum")
  print("4. Find Minimum")
  try:
    choice = int(input("Enter your choice (1/2/3/4): "))
    if choice not in [1, 2, 3, 4]:
      print("Invalid choice. Please enter 1/2/3/4")
      return
    
    user_input = input("Enter a list of numbers separated by spaces: ")
    numbers = list(map(float, user_input.split()))

    if not numbers:
      print("Numbers cannot be zero")
      return
    if choice == 1:
      print(f"Sum of numbers: {calculate_sum(numbers)}")
    elif choice == 2:
      print(f"Average of numbers: {calculates_average(numbers)}")
    elif choice == 3:
      print(f"Maximum value: {find_max(numbers)}")
    elif choice == 4:
      print(f"Minimum value: {find_min(numbers)}")
  except ValueError as e:
    print(f"Error: {e}. Please enter a valid list of numbers")
  except Exception as e:
    print(f"An unexpected error occurred: {e}")
if __name__ == "__main__":
  main()

4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
  
  return lst[::2] #using list slicing to get every element starting from the first one. 
  """
  general form is lst[start:stop:step]
  start: where the slicing starts (we leave it empty to start from the beginning)
  stop: Where the slicing ends (left empty to go until the end)
  strp: Every second element in this case
  """

numbers = [1,2,3,4,5,6]
result = extract_every_other(numbers)
print(result)

2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]  # Slice the list from start to end (inclusive)


numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)
print(result)  


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    return lst[::-1]  # Reverses the list using slicing. Here first semicolon means starting index second one for end and third -1 is step which is reverse


input_list = [1, 2, 3, 4, 5]
output_list = reverse_list(input_list)

print(output_list) 


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]  # Slicing to remove first and last elements

    """
    lst[1:-1]:
    The 1 indicates that the slice starts from the second element (index 1), skipping the first element.
    The -1 indicates that the slice stops before the last element (index -1), effectively removing the last element.
    """
# Example usage
input_list = [1, 2, 3, 4, 5]
output_list = remove_first_last(input_list)

print(output_list)  


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    return lst[:n]  # Slicing to get the first n elements
    """
    lst[:n]:
    The : before n means "start from the beginning of the list".
    The n means "take the first n elements".
    """
input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_first_n(input_list, n)

print(output_list) 


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    return lst[-n:]  # Slicing to get the last n elements
    """
    lst[-n:]:
    The -n means "start from the n-th element from the end" (negative indexing).
    The : after -n means "take all elements from that position to the end of the list".
    """
# Example usage
input_list = [1, 2, 3, 4, 5]
n = 2
output_list = get_last_n(input_list, n)

print(output_list) 


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]  # Start from second-to-last, skip every second element, move backward
    """ 
    lst[-2::-2]:
    The -2 means "start from the second-to-last element."
    The :: indicates slicing, and the -2 after the second colon means "take every second element while moving backward."
    """
# Example usage
input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)

print(output_list)  


4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    flattened = []
    for sublist in lst:
        for item in sublist:
            flattened.append(item)
    return flattened

nested_list = [[1, 2], [3, 4], [5]]
flattened_list = flatten(nested_list)

print(flattened_list)  


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    element = lst  # Start with the outer list
    for index in indices:  # Loop through each index in the indices list
        element = element[index]  # Move to the next level using the current index
    return element  # Return the final element after all index levels


nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)

print(result) 


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    total = 0  # Start with a total sum of 0
    for element in lst:  # Iterate through each element in the list
        if isinstance(element, list):  # Check if the element is a list
            total += sum_nested(element)  # Recursively sum the nested list
        else:
            total += element  # If it's a number, add it to the total
    return total  # Return the final sum


nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)  # Output: 21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    # Iterate through each sublist or element in lst
    result = []  # Initialize an empty list to hold the modified sublists
    for item in lst:
        if isinstance(item, list):  # If the item is a sublist
            # Recursively remove elem from the sublist
            result.append(remove_element(item, elem))
        else:
            # If the item is not equal to elem, add it to the result list
            if item != elem:
                result.append(item)
    return result


lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
result = remove_element(lst, elem)
print(result) 

5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    # Initialize a variable to keep track of the maximum value
    max_value = float('-inf')  # Start with the smallest possible value

    # Iterate through each item in the list
    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, recurse on it
            max_value = max(max_value, find_max(item))  # Recursive call
        else:
            # If it's a number, compare it with the current max_value
            max_value = max(max_value, item)
    
    return max_value
lst = [[1, 2], [3, [4, 5]], 6]
result = find_max(lst)
print(result)  


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    count = 0  # Initialize a counter to track occurrences
    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, recurse on it
            count += count_occurrences(item, elem)
        else:
            # If the item is equal to elem, increment the count
            if item == elem:
                count += 1
    return count


lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
result = count_occurrences(lst, elem)
print(result)  


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    flattened = []
    for item in lst:
        if isinstance(item, list):  # If the item is a list, recursively flatten it
            flattened.extend(deep_flatten(item))
        else:
            flattened.append(item)  # If it's not a list, add it directly to the result
    return flattened

# Example usage:
nested_lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_lst)
print(result)  # Output: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    # Function to flatten the nested list
    def flatten(lst):
        flattened = []
        for item in lst:
            if isinstance(item, list):  # If item is a list, recurse
                flattened.extend(flatten(item))  # Add flattened items from the sublist
            else:
                flattened.append(item)  # If item is not a list, add it directly
        return flattened
    
    # Flatten the list
    flattened_lst = flatten(lst)
    
    # Calculate the sum of the flattened list
    total_sum = sum(flattened_lst)
    
    # Calculate the number of elements
    count = len(flattened_lst)
    
    # Calculate and return the average
    if count == 0:  # Avoid division by zero
        return 0
    return total_sum / count


nested_lst = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_lst)
print(result) 


10 To - Do - NumPy
Please complete all the problems listed below:
10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [10]:
import numpy as np

empty_array = np.empty((2,2))
print("\nEmpty Array:\n",empty_array)

one_array =np.ones((4,2))
print("\nOnes array\n", one_array)

filled_array = np.full((3,3), 9)
print("\nFilled array with value 9 :\n",filled_array)

zeros_array = np.zeros_like(one_array)
print("\nZeros Array with Same Shape as one_array\n", zeros_array)

existing_array = np.array([[1,2],[3,4]])
ones_like_array = np.ones_like(existing_array)
print("\nOnes Array with Same Shape as Existing Array:\n", ones_like_array)

new_list = [4,5,6,7]
numpy_array = np.array(new_list)
print("\nNumPy Array from List:", numpy_array)


Empty Array:
 [[1.94167799e-321 7.14059536e-312]
 [7.14291206e-312 7.14291207e-312]]

Ones array
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled array with value 9 :
 [[9 9 9]
 [9 9 9]
 [9 9 9]]

Zeros Array with Same Shape as one_array
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones Array with Same Shape as Existing Array:
 [[1 1]
 [1 1]]

NumPy Array from List: [4 5 6 7]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [11]:
import numpy as np

# 1: Array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("Array with values ranging from 10 to 49:\n", array_10_49)

# 2: 3x3 Matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

# 3: 3x3 Identity Matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4: Random Array of size 30 and Mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of Size 30:\n", random_array)
print("Mean of the Array:", mean_value)

# 5: 10x10 Random Array with Min and Max Values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\nRandom 10x10 Array:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# 6: Zero Array with 5th Element Replaced with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th Element Replaced with 1:\n", zero_array)

# 7: Reverse Array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# 8: 2D Array with 1 on Border and 0 Inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)

# 9: 8x8 Checkerboard Pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of Size 30:
 [0.82953375 0.37098061 0.67653613 0.00404617 0.59154553 0.05563211
 0.11012406 0.65009265 0.79547334 0.98136297 0.30024982 0.25698651
 0.60201375 0.83552041 0.26966284 0.31557791 0.37080464 0.30753992
 0.07715427 0.3102303  0.84732584 0.55255538 0.72046487 0.90985288
 0.65301159 0.69243563 0.94320918 0.97781626 0.29937159 0.43599836]
Mean of the Array: 0.524770309040321

Random 10x10 Array:
 [[0.16202598 0.26983407 0.89889028 0.54670204 0.94510143 0.26338301
  0.80673069 0.57063901 0.77306925 0.786487  ]
 [0.24494331 0.70962829 0.87149096 0.90687497 0.23623926 0.39339001
  0.687221   0.82162945 0.29311585 0.58656691]
 [0.09369819 0.64970204 0.50001912 0.89633808 0.89775173 

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [13]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
addition_result = x + y
print("Addition of x and y:\n", addition_result)

# 2. Subtract the two arrays
subtraction_result = x - y
print("\nSubtraction of x and y:\n", subtraction_result)

# 3. Multiply the array with any integer
multiplication_result = x * 2
print("\nMultiplying x by 2:\n", multiplication_result)

# 4. Square of each element
square_result = np.square(x)
print("\nSquare of each element in x:\n", square_result)

# 5. Dot product between v and w, x and v, x and y
dot_v_w = np.dot(v, w)
print("\nDot product of v and w:", dot_v_w)

dot_x_v = np.dot(x, v)
print("\nDot product of x and v:\n", dot_x_v)

dot_x_y = np.dot(x, y)
print("\nDot product of x and y:\n", dot_x_y)

# 6. Concatenate x and y along the row, v and w along the column
concat_x_y_row = np.concatenate((x, y), axis=1)
print("\nConcatenation of x and y along the row:\n", concat_x_y_row)

concat_v_w_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\nConcatenation of v and w along the column:\n", concat_v_w_col)

v_w_vstack = np.vstack((v, w))
print("\nConcatenation of v and w using np.vstack():\n", v_w_vstack)

# 7. Concatenate x and v (expect error)
try:
    concat_x_v = np.concatenate((x, v), axis=1)
except Exception as e:
    print("\nError while concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplying x by 2:
 [[ 2  4]
 [ 6 10]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along the row:
 [[1 2 5 6]
 [3 5 7 8]]

Concatenation of v and w along the column:
 [[ 9 11]
 [10 12]]

Concatenation of v and w using np.vstack():
 [[ 9 10]
 [11 12]]

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT

In [15]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I (Identity Matrix)
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
# Set a tolerance to round values close to zero
identity_matrix = np.round(identity_matrix, decimals=6)
print("A * A^-1:\n", identity_matrix)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
B_T = np.transpose(B)
A_T = np.transpose(A)
B_T_A_T = np.dot(B_T, A_T)
print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", B_T_A_T)


A * A^-1:
 [[1. 0.]
 [0. 1.]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [16]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])

# Constants vector B
B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using the inverse method: X = A_inv * B
X = np.dot(A_inv, B)

print("Solution (x, y, z):", X)


Solution (x, y, z): [ 2.  1. -2.]


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [17]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])

# Constants vector B
B = np.array([-1, -3, 9])

# Compute the inverse of matrix A using np.linalg.inv
A_inv = np.linalg.inv(A)

# Solve for X using the inverse of A: X = A_inv * B
X = np.dot(A_inv, B)

print("Solution (x, y, z):", X)


Solution (x, y, z): [ 2.  1. -2.]


Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

In [18]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]

# Start measuring time
start_time = time.time()

# Perform element-wise addition of the two lists
result = [list1[i] + list2[i] for i in range(len(list1))]

# Measure the time taken for the operation
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise addition: {end_time - start_time} seconds")


Time taken for element-wise addition: 0.09171795845031738 seconds


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [19]:
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)
array2 = np.arange(1000001, 2000001)

# Start measuring time
start_time = time.time()

# Perform element-wise addition of the two arrays
result = array1 + array2

# Measure the time taken for the operation
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise addition with NumPy: {end_time - start_time} seconds")


Time taken for element-wise addition with NumPy: 0.035826921463012695 seconds


Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

In [20]:
import time


list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]

# Start measuring time
start_time = time.time()

# Perform element-wise multiplication of the two lists
result = [list1[i] * list2[i] for i in range(len(list1))]

# Measure the time taken for the operation
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise multiplication with Python lists: {end_time - start_time} seconds")


Time taken for element-wise multiplication with Python lists: 0.10440826416015625 seconds


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [21]:
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)
array2 = np.arange(1000001, 2000001)

# Start measuring time
start_time = time.time()

# Perform element-wise multiplication of the two arrays
result = array1 * array2

# Measure the time taken for the operation
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise multiplication with NumPy: {end_time - start_time} seconds")


Time taken for element-wise multiplication with NumPy: 0.023409128189086914 seconds


Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

In [22]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]

# Start measuring time
start_time = time.time()

# Compute dot product of the two lists using list comprehension and sum
dot_product = sum(list1[i] * list2[i] for i in range(len(list1)))

# Measure the time taken for the operation
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for dot product with Python lists: {end_time - start_time} seconds")


Time taken for dot product with Python lists: 0.29549431800842285 seconds


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [23]:
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)
array2 = np.arange(1000001, 2000001)

# Start measuring time
start_time = time.time()

# Compute dot product of the two arrays using NumPy
dot_product = np.dot(array1, array2)

# Measure the time taken for the operation
end_time = time.time()

# Print the dot product and the time taken for the operation
print(f"Dot product: {dot_product}")
print(f"Time taken for dot product with NumPy: {end_time - start_time} seconds")


Dot product: 833334333333500000
Time taken for dot product with NumPy: 0.002993345260620117 seconds


Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [24]:
import time

# Initialize two 1000x1000 matrices
matrix1 = [[i for i in range(1000)] for _ in range(1000)]  # Matrix 1 of size 1000x1000
matrix2 = [[i for i in range(1000)] for _ in range(1000)]  # Matrix 2 of size 1000x1000

# Start measuring time
start_time = time.time()

# Initialize an empty matrix to store the result
result_matrix = [[0] * 1000 for _ in range(1000)]

# Perform matrix multiplication
for i in range(1000):
    for j in range(1000):
        result_matrix[i][j] = sum(matrix1[i][k] * matrix2[k][j] for k in range(1000))

# Measure the time taken for the operation
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for matrix multiplication with Python lists: {end_time - start_time} seconds")


Time taken for matrix multiplication with Python lists: 134.6692316532135 seconds


Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [25]:
import numpy as np
import time

# Create two random 1000x1000 matrices
matrix1 = np.random.rand(1000, 1000)
matrix2 = np.random.rand(1000, 1000)

# Measure time before multiplication
start_time = time.time()

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

# Measure time after multiplication
end_time = time.time()

# Print the time taken
print("Time taken for matrix multiplication:", end_time - start_time, "seconds")


Time taken for matrix multiplication: 0.026388168334960938 seconds
